const assert=require('node:assert/strict');
const fs=require('fs');
const vm=require('vm');
function load(env,query){
 const module={exports:{}};
 vm.runInNewContext(fs.readFileSync(require.resolve('../designs'),'utf8'),{module,console,Buffer,process:{env},require(n){if(n==='./db')return {query};if(n==='./design-assets')return {makePublic:async()=>{}};if(n.startsWith('./'))return require(require.resolve('../' + n.slice(2)));return require(n);}});
 return module.exports;
}
(async()=>{
 const body={title:'Test',canvas:{width:600,height:400},elements:[{id:'one',type:'text',text:'Editable'}]};
 const local=load({},()=>{throw Error('No DB calls expected');});
 const initial=await local.listTemplates('all');
 assert(initial.templates.length>0);assert(initial.templates.every(t=>t.likes===0&&t.uses===0),'Built-in fallback templates must not invent popularity');
 const canonical=initial.templates.find(t=>t.id==='dt_heygen_trick');
 const legacy={id:canonical.id,title:canonical.title,source_type:'shortscraft_official',canvas:{width:1280,height:720,isPremium:true},elements:[],author_handle:'shortscraft',status:'published'};
 const restored=local.publicTemplate(legacy);
 assert(restored.elements.length>10); assert.equal(restored.canvas.width,1024); assert.equal(restored.isPremium,true);
 assert.equal(legacy.elements.length,0,'Read repair must not mutate database input');
 const alias=local.publicTemplate({...legacy,id:'dt_ai_breakthrough',preview_url:'/storage/designs/templates/heygen-trick.webp',title:'AI Breakthrough Tech Thumbnail'});
 assert.equal(alias.elements.length,canonical.elements.length); assert.equal(alias.title,'AI Breakthrough Tech Thumbnail'); assert.equal(alias.restoredFromTemplateId,canonical.id);
 assert.equal(local.publicTemplate({...legacy,id:'dt_ai_breakthrough',preview_url:'/different-art.webp'}).editable,false,'Unknown artwork must not receive unrelated layers');
 assert.equal(local.publicTemplate({...legacy,source_type:'creator_original'}).editable,false,'Never invent creator layers');
 assert.equal(local.publicTemplate({...legacy,elements:[{id:'custom',type:'text',text:'Creator edit'}]}).elements[0].text,'Creator edit','Keep actual stored content');
 assert.equal((await local.saveProject(null,'new',body)).status,401);
 const a=await local.saveProject('alice','new',body),b=await local.saveProject('alice','new',body);
 assert(a.success&&b.success);assert.notEqual(a.project.id,b.project.id);
 assert.equal((await local.saveProject('bob',a.project.id,body)).status,403);
 assert.equal((await local.getProject('bob',a.project.id)).status,404);
 assert.equal((await local.getProject('alice',a.project.id)).project.elements[0].text,'Editable');
 const cloned=await local.cloneTemplate('alice',canonical.id);
 assert(cloned.success); assert(cloned.project.elements.length>10); assert.equal(cloned.project.source.parentTemplateId,canonical.id);
 const down=load({DATABASE_URL:'offline-placeholder',NODE_ENV:'production'},async()=>{throw Error('simulated outage');});
 const oldCopy=await local.saveProject('alice','new',{...body,name:canonical.title+' (Copy)',source:{type:'scratch'}});
 assert.equal((await local.getProject('alice',oldCopy.project.id)).project.recoveryTemplateId,canonical.id,'Offer non-destructive recovery for an old blank clone');
 assert.equal((await down.saveProject('alice','new',body)).status,503);
 assert.equal((await down.listProjects('alice')).status,503);
 assert.equal((await down.publishTemplate({id:'alice'},body)).status,503);
 const missing=load({NODE_ENV:'production'},()=>{});
 assert.equal((await missing.saveProject('alice','new',body)).status,503);
 console.log('PASS unique new IDs, save/reopen, owner isolation, outage reporting and no production memory-only success.');
})().catch(e=>{console.error(e);process.exitCode=1;});
